INSERT INTO genero (nome)
VALUES
    ('Ação e aventura'),
    ('Ficção afro-americana'),
    ('Antologias'),
    ('Infantil'),
    ('Grau médio'),
    ('Fantasia de grau médio'),
    ('Livros de imagens'),
    ('Ficção Cristã'),
    ('Clássicos'),
    ('Quadrinhos e romances gráficos'),
    ('Chegando à maioridade'),
    ('Ficção Contemporânea'),
    ('Cultural e étnico'),
    ('Fantasia'),
    ('Fantasia épica'),
    ('Jogos e LitRPG'),
    ('Fantasia Urbana'),
    ('Ficção histórica'),
    ('Humor e comédia'),
    ('Ficção LGBTQ'),
    ('Ficção Literária'),
    ('Realismo mágico'),
    ('Mashups'),
    ('Mistério e crime'),
    ('Mistérios aconchegantes'),
    ('Mistérios Históricos'),
    ('Peças e roteiros'),
    ('Poesia'),
    ('Romance'),
    ('Romance contemporâneo'),
    ('Romance histórico'),
    ('Romance Paranormal'),
    ('Comédia romântica'),
    ('Suspense Romântico'),
    ('Romance de viagem no tempo'),
    ('Ficção científica'),
    ('Distópico'),
    ('Ficção científica militar'),
    ('Pós-apocalíptico'),
    ('Space Opera'),
    ('Steampunk (e outros gêneros punk na ficção)'),
    ('Viagem no tempo'),
    ('Contos'),
    ('Temáticas e motivações'),
    ('Thriller e Suspense'),
    ('Espionagem'),
    ('Horror'),
    ('Thriller legal'),
    ('Thriller médico'),
    ('Thriller psicológico'),
    ('Technothriller'),
    ('Ficção Feminina'),
    ('Chick Lit'),
    ('Jovem adulto'),
    ('Novo Adulto'),
    ('Questões Sociais e Familiares'),
    ('Fantasia para jovens adultos');