INSERT INTO genero (nome)
VALUES
    ('Ação e aventura'),
    ('Ficção afro-americana'),
    ('Antologias'),
    ('Infantil'),
    ('Grau médio'),
    ('Livros de imagens'),
    ('Ficção Cristã'),
    ('Clássicos'),
    ('Ficção Contemporânea'),
    ('Cultural e étnico'),
    ('Fantasia'),
    ('Fantasia épica'),
    ('Jogos e LitRPG'),
    ('Fantasia Urbana'),
    ('Ficção histórica'),
    ('Humor e comédia'),
    ('Ficção LGBTQIA+'),
    ('Ficção Literária'),
    ('Mashups'),
    ('Mistério e crime'),
    ('Mistérios Históricos'),
    ('Peças e roteiros'),
    ('Poesia'),
    ('Romance'),
    ('Romance contemporâneo'),
    ('Romance histórico'),
    ('Romance Paranormal'),
    ('Comédia romântica'),
    ('Ficção científica'),
    ('Distópico'),
    ('Pós-apocalíptico'),
    ('Space Opera'),
    ('Steampunk'),
    ('Viagem no tempo'),
    ('Contos'),
    ('Temáticas e motivações'),
    ('Thriller e Suspense'),
    ('Espionagem'),
    ('Horror'),
    ('Thriller'),
    ('Chick Lit'),
    ('Jovem adulto'),
    ('Novo Adulto'),
    ('Questões Sociais e Familiares'),
    ('Fantasia');

INSERT INTO frase (frase, autor)
VALUES
  ('O que a literatura faz é o mesmo que acender um fósforo no campo no meio da noite. Um fósforo não ilumina quase nada, mas nos permite ver quanta escuridão existe ao redor.', 'William Faulkner'),
  ('Isso é parte da beleza de toda a literatura. Você descobre que seus desejos são desejos universais, que você não está só e isolado de todo o mundo. Você pertence.', 'F. Scott Fitzgerald'),
  ('Enquanto o pensamento existe, as palavras estão vivas e a literatura se torna uma fuga, não da, mas para a vida.', 'Cyril Connolly'),
  ('A literatura é a maneira mais agradável de ignorar a vida.', 'Fernando Pessoa'),
  ('A literatura possibilita uma introspecção muito mais profunda às pessoas do que qualquer outra ciência o pode fazer.', 'Noam Chomsky'),
  ('A Literatura nos ensina a perceber melhor quem somos, a questionar o que poderíamos ter sido e a projetar o que poderemos vir a ser.', 'Ana Teresa Peixinho'),
  ('Cada livro, cada volume que você vê, tem uma alma. A alma de quem o escreveu, e a alma dos que o leram, que viveram e sonharam com ele.', 'Carlos Ruiz Zafón'),
  ('Literatura é a linguagem carregada de significado.', 'Ezra Pound'),
  ('A literatura não é algo que nos faça felizes, mas ajuda-nos a defendermo-nos da infelicidade.', 'Mário Vargas Llosa'),
  ('Literatura: arte de desenhar e pintar com palavras.', 'E. Pasqua');