spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/writerscircle
    username: wcircle
    password: wcircle
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
